### PR TITLE
Fixed not set fields when emailAsUsername is set before fields are set.

### LINKED ISSUE #130: PFLogInViewController: no Facebook button with emailAsUserName
I suppose it's because of my Swift implementation, but I can't have the Facebook button appear in the PFLogInViewController.
This is not due to FB integration, since using only the standard FB login button instead of a PFLogInViewController works perfectly.

Looking in StackOverflow, it appears I'm not the only one with this issue.

### PR DESCRIPTION
**Pull request by nlutsenko**
- Made `fields` property PFLogInView be readwrite, but only privately, which ultimately resolved the bug
- Made `fields` property on PFLogInViewController change `fields` of PFLogInView, which makes it work as expected.

Fixes #130

### CODE REVIEW

File: ParseUI/Classes/LogInViewController/PFLogInView.m [hunk 1]
```diff
@@ -286,7 +337,8 @@ - (void)layoutSubviews {
         CGFloat loginButtonTopInset = floorf(24.0f * contentSizeScale.height);
 
         CGRect frame = PFRectMakeWithSizeCenteredInRect([_logInButton sizeThatFits:loginContentSize],
-                                                        loginContentRect);;
+                                                        loginContentRect);
+        ;
```
Comment (richardjrossiii) [inline ParseUI/Classes/LogInViewController/PFLogInView.m]: Kill.
